# Generated by Django 4.1.2 on 2023-06-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attentiondata',
            old_name='position',
            new_name='scroll_position',
        ),
        migrations.RenameField(
            model_name='attentiondata',
            old_name='dwell_time',
            new_name='stay_time',
        ),
        migrations.RemoveField(
            model_name='attentiondata',
            name='page',
        ),
        migrations.RemoveField(
            model_name='attentiondata',
            name='user',
        ),
    ]
