# Generated by Django 4.1.2 on 2023-06-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpanalysis', '0002_rename_position_attentiondata_scroll_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attentiondata',
            name='scroll_position',
        ),
        migrations.RemoveField(
            model_name='attentiondata',
            name='stay_time',
        ),
        migrations.AddField(
            model_name='attentiondata',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
