# Generated by Django 4.1.2 on 2023-06-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpanalysis', '0003_remove_attentiondata_scroll_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attentiondata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
