# Generated by Django 4.1.2 on 2023-06-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpanalysis', '0004_alter_attentiondata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attentiondata',
            name='data',
        ),
        migrations.AddField(
            model_name='attentiondata',
            name='scroll_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attentiondata',
            name='stay_time',
            field=models.FloatField(default=0),
        ),
    ]
