# Generated by Django 4.1.2 on 2023-06-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpanalysis', '0005_remove_attentiondata_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attentiondata',
            old_name='scroll_position',
            new_name='attention_position',
        ),
    ]
